version: "3.7"
        
services:
    mysqldb:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: embulk_mysqldb
            MYSQL_USER: mysql
            MYSQL_PASSWORD: password

    pgdb:
        container_name: pgdb
        image: postgres:9.6-alpine
        restart: always
        ports: 
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: embulk_pgdb

    adminer:
        container_name: adminer
        image: adminer:4-standalone
        restart: always
        depends_on:
            - mysqldb
            - pgdb
        ports:
            - 8080:8080
